#!/usr/bin/env bash

set -e

sudo apt update && sudo apt install -y curl gnupg2 lsb-release

ARCH=$(uname -i)
RELEASE=$(lsb_release -c -s)

eloquentx86_64=https://github.com/ros2/ros2/releases/download/release-eloquent-2020-1212/ros2-eloquent-20201212-linux-bionic-amd64.tar.bz2
eloquentaarch64=https://github.com/ros2/ros2/releases/download/release-eloquent-2020-1212/ros2-eloquent-20201212-linux-bionic-arm64.tar.bz2        
foxyx86_64=https://github.com/ros2/ros2/releases/download/release-foxy-20201211/ros2-foxy-20201211-linux-focal-amd64.tar.bz2
foxyaarch64=https://github.com/ros2/ros2/releases/download/release-foxy-20201211/ros2-foxy-20201211-linux-focal-arm64.tar.bz2

if [ $RELEASE == "bionic" ]
    then
        ROSDISTRO=eloquent

elif [ $RELEASE == "focal" ]
    then
        ROSDISTRO=foxy
else
    echo "$RELEASE OS Release not supported. Exiting now"
    exit
fi

if [ $ARCH != "x86_64" ] && [ $ARCH != "aarch64" ]
    then
        echo "$ARCH architecture not supported. Exiting now"
        exit
fi

RELEASE_FILE=$ROSDISTRO$ARCH

# Add the ROS 2 apt repository
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg

# Add repository to sources list
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

# Download ROS2
echo "Downloading $ROSDISTRO-$ARCH release from github. This may take a while ..."
cd /tmp
curl -sSL ${!RELEASE_FILE} -o ros-$ROSDISTRO-$ARCH.tar.bz2

mkdir -p ~/ros2_$ROSDISTRO
cd ~/ros2_$ROSDISTRO
tar xf /tmp/ros-$ROSDISTRO-$ARCH.tar.bz2

echo "Installing ROS $ROSDISTRO on $ARCH architecture"

# Install and initialize rosdep
sudo apt update
sudo apt install -y python3-rosdep
sudo rosdep init
rosdep update

# Install missing dependencies
if [ $ROSDISTRO == "eloquent" ]
    then
        rosdep install --from-paths ~/ros2_$ROSDISTRO/ros2-linux/share --ignore-src --rosdistro $ROSDISTRO -y --skip-keys "console_bridge fastcdr fastrtps libopensplice67 libopensplice69 osrf_testing_tools_cpp poco_vendor rmw_connext_cpp rosidl_typesupport_connext_c rosidl_typesupport_connext_cpp rti-connext-dds-5.3.1 tinyxml_vendor tinyxml2_vendor urdfdom urdfdom_headers"

elif [ $ROSDISTRO == "foxy" ]
    then
        rosdep install --from-paths ~/ros2_$ROSDISTRO/ros2-linux/share --ignore-src --rosdistro $ROSDISTRO -y --skip-keys "console_bridge fastcdr fastrtps osrf_testing_tools_cpp poco_vendor rmw_connextdds rti-connext-dds-5.3.1 tinyxml_vendor tinyxml2_vendor urdfdom urdfdom_headers"
fi

# Install python3 libraries
sudo apt install -y libpython3-dev python3-pip
pip3 install -U argcomplete

echo ""
echo "ROS $ROSDISTRO installation complete!"
echo ""

echo "Set up your environment by sourcing the following file."
echo ". ~/ros2_$ROSDISTRO/ros2-linux/setup.bash"
echo ""

echo -n "Or do you want to save this on your .bashrc (y/n)? "
read answer

if [ "$answer" != "${answer#[Yy]}" ] ;then
    echo ". ~/ros2_$ROSDISTRO/ros2-linux/setup.bash" >> ~/.bashrc
fi
